import { Component, OnInit } from '@angular/core';
import {NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';
import {ToastrService} from 'ngx-toastr';
import {NgForm} from '@angular/forms';
import {RESTAPIService} from '../../services/REST-API.service';


@Component({
  selector: 'app-user-assign-confirmation-modal',
  templateUrl: './user-assign-confirmation-modal.component.html'
})
export class UserAssignConfirmationModalComponent {
  data: any = {};
  messageDialog = false;

  constructor(public activeModal: NgbActiveModal,private restAPIService: RESTAPIService,) { }

  ngOnInit(): void {
    console.log('data', this.data);
  }

  cancel () {
    this.activeModal.dismiss();
  }

  sendEmail(){
    let obj = {
      showDialog: this.messageDialog
    }
    this.activeModal.close(obj);
  //   return;
  //   const sendEmailObj: any = {};
  //   sendEmailObj.RecipientsList = this.data.email;
  //   sendEmailObj.ContractNo = this.data.contractNo;
  //   sendEmailObj.Title = this.data.title;
  //   sendEmailObj.__metadata = { type: 'SP.Data.AutoGeneratedEmailsOnDemandListItem' }

  //   this.restAPIService.saveAutoGeneratedEmailsOnDemand(sendEmailObj).subscribe((response: any) => {
  //     if (this.restAPIService.isSuccessResponse(response)) {
  //       this.activeModal.close(this.messageDialog);
  //     }
  //   })
  }

}
